# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# https://go.microsoft.com/fwlink/?LinkID=615561

# Builds the library and test suite.

schedules:
  - cron: "30 5 * * *"
    displayName: 'Nightly build'
    branches:
      include:
        - main

# GitHub Actions handles test suite for CI/PR
trigger: none
pr:
  branches:
    include:
      - main
  paths:
    include:
      - '.azuredevops/pipelines/DirectXTK12-GitHub-Test.yml'

resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main
    - repository: testRepo
      name: walbourn/directxtk12test
      type: github
      endpoint: microsoft
      ref: refs/heads/main

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

pool:
  vmImage: windows-2022

variables:
  - group: dxtk-shared-variables
  - name: Codeql.Enabled
    value: false
  - name: GUID_FEED
    value: $(ADOFeedGUID)

jobs:
  - job: DESKTOP_BUILD
    displayName: 'Windows Desktop'
    timeoutInMinutes: 120
    cancelTimeoutInMinutes: 1
    workspace:
      clean: all
    strategy:
      maxParallel: 2
      matrix:
        Release_x64:
          BuildPlatform: x64
          BuildConfiguration: Release
        Debug_x64:
          BuildPlatform: x64
          BuildConfiguration: Debug
        Release_x86:
          BuildPlatform: x86
          BuildConfiguration: Release
        Debug_x86:
          BuildPlatform: x86
          BuildConfiguration: Debug
    steps:
      - checkout: self
        clean: true
        fetchTags: false
        fetchDepth: 1
        path: 's'
      - checkout: testRepo
        displayName: Fetch Tests
        clean: true
        fetchTags: false
        fetchDepth: 1
        path: 's/Tests'
      - task: NuGetToolInstaller@1
        displayName: 'Use NuGet'
      - task: NuGetAuthenticate@1
        displayName: 'NuGet Auth'
      - task: NuGetCommand@2
        displayName: NuGet restore tests
        inputs:
          solution: Tests/D3D12Test/packages.config
          feedRestore: $(GUID_FEED)
          includeNuGetOrg: false
          packagesDirectory: ../packages
      - task: VSBuild@1
        displayName: Build solution DirectXTK_Tests_Desktop_2019_Win10.sln
        inputs:
          solution: Tests/DirectXTK_Tests_Desktop_2019_Win10.sln
          msbuildArgs: /p:PreferredToolArchitecture=x64
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
      - task: VSBuild@1
        displayName: Build solution DirectXTK_Tests_Desktop_2019_AgilitySDK.sln
        inputs:
          solution: Tests/DirectXTK_Tests_Desktop_2019_AgilitySDK.sln
          msbuildArgs: /p:PreferredToolArchitecture=x64
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
