# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# http://go.microsoft.com/fwlink/?LinkID=615561

# Builds the library for Windows Desktop and UWP.

schedules:
  - cron: "5 5 * * *"
    displayName: 'Nightly build'
    branches:
      include:
        - main

# GitHub Actions handles MSBuild for CI/PR
trigger: none
pr:
  branches:
    include:
      - main
  paths:
    include:
      - '.azuredevops/pipelines/DirectXTK12-GitHub.yml'
      - Src/Shaders/CompileShaders.cmd

resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

variables:
  Codeql.Enabled: false

pool:
  vmImage: windows-2019

jobs:
  - job: DESKTOP_BUILD
    displayName: 'Windows Desktop'
    timeoutInMinutes: 120
    cancelTimeoutInMinutes: 1
    strategy:
      maxParallel: 2
      matrix:
        Release_x64:
          BuildPlatform: x64
          BuildConfiguration: Release
        Debug_x64:
          BuildPlatform: x64
          BuildConfiguration: Debug
        Release_x86:
          BuildPlatform: x86
          BuildConfiguration: Release
        Debug_x86:
          BuildPlatform: x86
          BuildConfiguration: Debug
    steps:
      - checkout: self
        clean: true
        fetchTags: false
      - task: VSBuild@1
        displayName: Build solution DirectXTK_Desktop_2019_Win10.sln
        inputs:
          solution: DirectXTK_Desktop_2019_Win10.sln
          msbuildArgs: /p:PreferredToolArchitecture=x64
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
